name: 'Release'

on:
  push:
    tags:
    - 'v*'

jobs:
  goreleaser:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Unshallow'
        run: 'git fetch --prune --unshallow'

      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.19'

      - name: 'Import GPG key'
        id: 'import_gpg'
        uses: 'crazy-max/ghaction-import-gpg@v5'
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          passphrase: '${{ secrets.PASSPHRASE }}'

      - name: 'Run GoReleaser'
        uses: 'goreleaser/goreleaser-action@v3'
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GPG_FINGERPRINT: '${{ steps.import_gpg.outputs.fingerprint }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
